spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_api
    username: root
    password: 35828889
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
spring-doc:
  pathsToMatch: /api/**/v1/**

swagger-ui:
  use-root-path: true